#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-calcite-avatica
Version  : 1.2.0.incubating
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/calcite/calcite-avatica/1.2.0-incubating/calcite-avatica-1.2.0-incubating.jar
Source0  : https://repo1.maven.org/maven2/org/apache/calcite/calcite-avatica/1.2.0-incubating/calcite-avatica-1.2.0-incubating.jar
Source1  : https://repo1.maven.org/maven2/org/apache/calcite/calcite-avatica/1.2.0-incubating/calcite-avatica-1.2.0-incubating.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-calcite-avatica-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-calcite-avatica package.
Group: Data

%description data
data components for the mvn-calcite-avatica package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/calcite/calcite-avatica/1.2.0-incubating
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/calcite/calcite-avatica/1.2.0-incubating

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/calcite/calcite-avatica/1.2.0-incubating
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/calcite/calcite-avatica/1.2.0-incubating


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/calcite/calcite-avatica/1.2.0-incubating/calcite-avatica-1.2.0-incubating.jar
/usr/share/java/.m2/repository/org/apache/calcite/calcite-avatica/1.2.0-incubating/calcite-avatica-1.2.0-incubating.pom
